name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true
        id: go
      - name: env
        run: go env
      - name: build
        run: go build ./...

  test:
    runs-on: ubuntu-latest
      - name: set up
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true
        id: go
      - name: test
        run: go test ./... -v
